-- ============================================================================
-- Sequences for Epic 0.1 objects
-- ============================================================================

CREATE SEQUENCE SEQ_CM_CUSTOMER          START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_ACCOUNT           START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_CARD_PRODUCT      START WITH 100  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_CARD              START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_TOKEN_VAULT       START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_CDE_ASSET_SCOPE   START WITH 10   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_AUDIT_LOG         START WITH 1    INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_USER_ROLE_MAP     START WITH 100  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_DATA_ACCESS_LOG   START WITH 1    INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_OFAC_WATCHLIST    START WITH 1    INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CM_OFAC_SCREEN_RSLT  START WITH 1    INCREMENT BY 1 NOCACHE NOCYCLE;
