-- ============================================================================
-- Primary Key constraints - Epic 0.1
-- ============================================================================

ALTER TABLE CM_CUSTOMER          ADD CONSTRAINT PK_CM_CUSTOMER          PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE CM_ACCOUNT            ADD CONSTRAINT PK_CM_ACCOUNT           PRIMARY KEY (ACCOUNT_ID);
ALTER TABLE CM_CARD_PRODUCT       ADD CONSTRAINT PK_CM_CARD_PRODUCT      PRIMARY KEY (CARD_PRODUCT_ID);
ALTER TABLE CM_CARD                ADD CONSTRAINT PK_CM_CARD             PRIMARY KEY (CARD_ID);
ALTER TABLE CM_TOKEN_VAULT          ADD CONSTRAINT PK_CM_TOKEN_VAULT      PRIMARY KEY (TOKEN_ID);
ALTER TABLE CM_CDE_ASSET_SCOPE       ADD CONSTRAINT PK_CM_CDE_ASSET_SCOPE  PRIMARY KEY (ASSET_SCOPE_ID);
ALTER TABLE CM_AUDIT_LOG              ADD CONSTRAINT PK_CM_AUDIT_LOG       PRIMARY KEY (AUDIT_ID);
ALTER TABLE CM_ROLE                    ADD CONSTRAINT PK_CM_ROLE          PRIMARY KEY (ROLE_ID);
ALTER TABLE CM_USER_ROLE_MAP            ADD CONSTRAINT PK_CM_USER_ROLE_MAP PRIMARY KEY (USER_ROLE_MAP_ID);
ALTER TABLE CM_DATA_ACCESS_LOG           ADD CONSTRAINT PK_CM_DATA_ACCESS_LOG PRIMARY KEY (ACCESS_LOG_ID);
ALTER TABLE CM_OFAC_WATCHLIST              ADD CONSTRAINT PK_CM_OFAC_WATCHLIST PRIMARY KEY (WATCHLIST_ID);
ALTER TABLE CM_OFAC_SCREEN_RESULT           ADD CONSTRAINT PK_CM_OFAC_SCREEN_RESULT PRIMARY KEY (SCREEN_RESULT_ID);
