-- ============================================================================
-- Unique Key constraints - Epic 0.1
-- ============================================================================

ALTER TABLE CM_CUSTOMER      ADD CONSTRAINT UK_CUSTOMER_EMAIL      UNIQUE (EMAIL);
ALTER TABLE CM_ACCOUNT        ADD CONSTRAINT UK_ACCOUNT_NUMBER      UNIQUE (ACCOUNT_NUMBER);
ALTER TABLE CM_CARD_PRODUCT    ADD CONSTRAINT UK_CARDPRODUCT_CODE    UNIQUE (PRODUCT_CODE);
ALTER TABLE CM_TOKEN_VAULT      ADD CONSTRAINT UK_TOKEN_VALUE         UNIQUE (TOKEN_VALUE);
ALTER TABLE CM_TOKEN_VAULT       ADD CONSTRAINT UK_TOKEN_PAN_HASH      UNIQUE (PAN_HASH);   -- prevents issuing 2 tokens for same PAN
ALTER TABLE CM_ROLE               ADD CONSTRAINT UK_ROLE_NAME           UNIQUE (ROLE_NAME);
ALTER TABLE CM_USER_ROLE_MAP       ADD CONSTRAINT UK_USER_ACTIVE_ROLE    UNIQUE (APP_USER_ID, ROLE_ID, EFFECTIVE_DATE);
