-- ============================================================================
-- Check constraints - Epic 0.1
-- ============================================================================

-- CARD-001: product_type discriminator restricted to the 3 supported products
ALTER TABLE CM_CARD_PRODUCT
    ADD CONSTRAINT CK_CARDPRODUCT_TYPE
    CHECK (PRODUCT_TYPE IN ('DEBIT','CREDIT','PREPAID'));

ALTER TABLE CM_ACCOUNT
    ADD CONSTRAINT CK_ACCOUNT_TYPE
    CHECK (ACCOUNT_TYPE IN ('DEBIT','CREDIT','PREPAID'));

ALTER TABLE CM_ACCOUNT
    ADD CONSTRAINT CK_ACCOUNT_STATUS
    CHECK (ACCOUNT_STATUS IN ('ACTIVE','DORMANT','CLOSED','FROZEN'));

ALTER TABLE CM_CUSTOMER
    ADD CONSTRAINT CK_CUSTOMER_TYPE
    CHECK (CUSTOMER_TYPE IN ('CONSUMER','BUSINESS'));

ALTER TABLE CM_CUSTOMER
    ADD CONSTRAINT CK_CUSTOMER_STATUS
    CHECK (CUSTOMER_STATUS IN ('ACTIVE','INACTIVE','SUSPENDED','CLOSED'));

ALTER TABLE CM_CUSTOMER
    ADD CONSTRAINT CK_CUSTOMER_SSN_LAST4
    CHECK (REGEXP_LIKE(SSN_LAST4, '^[0-9]{4}$'));

ALTER TABLE CM_CARD
    ADD CONSTRAINT CK_CARD_STATUS
    CHECK (CARD_STATUS IN ('REQUESTED','ISSUED','ACTIVE','BLOCKED','CANCELLED','EXPIRED'));

-- CARD-005: role PAN visibility restricted to defined levels
ALTER TABLE CM_ROLE
    ADD CONSTRAINT CK_ROLE_PAN_VISIBILITY
    CHECK (PAN_VISIBILITY IN ('MASKED_LAST4','MASKED_FIRST6LAST4','FULL'));

ALTER TABLE CM_ROLE
    ADD CONSTRAINT CK_ROLE_NAME_VALUES
    CHECK (ROLE_NAME IN ('AGENT','ANALYST','ADMIN','COMPLIANCE'));

-- CARD-006: screen result restricted to defined outcomes
ALTER TABLE CM_OFAC_SCREEN_RESULT
    ADD CONSTRAINT CK_OFAC_RESULT_VALUES
    CHECK (SCREEN_RESULT IN ('MATCH','NO_MATCH','REVIEW'));

ALTER TABLE CM_OFAC_SCREEN_RESULT
    ADD CONSTRAINT CK_OFAC_PARTY_TYPE
    CHECK (PARTY_TYPE IN ('CUSTOMER','TRANSACTION_PARTY'));

-- CARD-004: audit log operation restricted
ALTER TABLE CM_AUDIT_LOG
    ADD CONSTRAINT CK_AUDITLOG_OPERATION
    CHECK (OPERATION IN ('INSERT','UPDATE','DELETE'));
